# Generated by Django 5.1.1 on 2024-10-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Максимум 100 символов', max_length=100, verbose_name='Название фильма')),
                ('description', models.TextField(verbose_name='Коротко о фильме')),
                ('image', models.ImageField(upload_to='', verbose_name='Фотография о фильме')),
                ('video', models.URLField(verbose_name='Видео')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
