# Generated by Django 5.1.1 on 2024-10-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_movie_duration_movie_genres_alter_movie_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(help_text='Максимум 50 символов', max_length=50, null=True, verbose_name='Режиссер'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.CharField(max_length=50, null=True, verbose_name='Продолжительность'),
        ),
    ]
